ls:
  .ts: kebab-case
  .tsx: kebab-case
  .js: kebab-case
  .jsx: kebab-case
  .json: kebab-case
  .md: kebab-case | SCREAMING_SNAKE_CASE
  .yml: kebab-case
  .yaml: kebab-case
  .hbs: kebab-case

ignore:
  - node_modules
  - dist
  - coverage
  - .git
